#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DSDL2COMPAT_TESTS=OFF \
    -DSDL2COMPAT_X11=OFF

cmake --build build
cmake --install build
