#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-rpath \
    --without-gphoto2 \
    --disable-nls \
    --disable-locking
	
make
make DESTDIR="$1" install
