#!/bin/sh -e

: > nostrip

export DESTDIR="$1"

patch -p1 < guile-3.0.10-c23.patch

export CFLAGS="$CFLAGS -std=gnu17"

./configure \
    --prefix=/usr \
    --program-suffix=3 \
    --enable-posix \
    --disable-error-on-warning \
    --enable-jit \
    --enable-netowrking \
    --disable-nls \
    --enable-regex \
    --with-threads

make
make install

rm -rf "$1/usr/share/info"
