#!/bin/sh -e

patch -p1 < fix_musl.patch

cd Project/GNU/Library

./autogen.sh

./configure \
    --prefix=/usr \
    --enable-shared \
    --disable-static \
    --with-libcurl \
    --with-libmms 
	
make
make DESTDIR="$1" install
