#!/bin/sh -e

# Set the compiler to gcc otherwise clang is needed
export TOOLCHAIN_FOR_TARGET=

# Support for uefi aarch64 disabled because it's unsupported
# in kiss

./configure \
	--prefix=/usr \
	--enable-all \
	--disable-uefi-aarch64 \
	--disable-uefi-riscv64 \
	--disable-uefi-loongarch64
	
make
make DESTDIR="$1" install
