#!/bin/sh -e

./configure \
    --sbindir=/usr/bin \
    --disable-ssh-token \
    --disable-nls \
    --disable-udev \
    --disable-external-tokens \
    --enable-static-cryptsetup \
    --with-crypto_backend=openssl

# Tests require additional dependencies, so we'll skip them.
sed '/^SUBDIRS = /s/tests//' Makefile > _
mv _ Makefile

make
make DESTDIR="$1" install

for bin in "$1/usr/bin/"*.static; do
    mv "$bin" "${bin%%.static}"
done
