#!/bin/sh -e

export CGO_CPPFLAGS="${CPPFLAGS}"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export CGO_LDFLAGS="${LDFLAGS}"
export GOFLAGS="-buildmode=pie -trimpath -ldflags=-linkmode=external -mod=readonly -modcacherw"

CGO_ENABLED=0 go build -trimpath -tags "e2e,kube" -o compose ./cmd

mkdir -p "$1/usr/bin" "$1/usr/lib/docker/cli-plugins"

cp compose "$1/usr/lib/docker/cli-plugins/docker-compose"
ln -sf /usr/lib/docker/cli-plugins/docker-compose "$1/usr/bin/docker-compose"
