#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

export CFLAGS="$CFLAGS \
    -DFZ_ENABLE_HTML=0 \
    -DFZ_ENABLE_HTML_ENGINE=0 \
    -DFZ_ENABLE_EPUB=0 \
    -DFZ_ENABLE_FB2=0 \
    -DFZ_ENABLE_ICC=0 \
    -DFZ_ENABLE_JPX=0 \
    -DFZ_ENABLE_JS=0 \
    -DFZ_ENABLE_MOBI=0 \
    -DFZ_ENABLE_OFFICE=0 \
    -DFZ_ENABLE_TXT=0 \
    -DNO_CJK \
    "

_args="
    html=no
    build=release
    shared=yes
    HAVE_X11=no
    HAVE_GLUT=no
    USE_SYSTEM_LIBS=yes
    USE_SYSTEM_OPENJPEG=no
    VENV_FLAG=
    "
# shellcheck disable=2086
make $_args
# shellcheck disable=2086
make $_args prefix=/usr DESTDIR="$1" install-shared-c

mkdir -p "$1/usr/lib/pkgconfig"
sed "s/@@VERSION@@/$2/" mupdf.pc.in > "$1/usr/lib/pkgconfig/mupdf.pc"
