#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Bashism banished.
export CONFIG_SHELL=/bin/sh

# Disable udev support by default since libudev-zero doesn't support it.
udev=disable

# libudev-zero trips (correctly) on the udev auto detection, but is broken with
# LVM2 (see https://github.com/illiliti/libudev-zero/issues/4). In order to
# turn it back on, uncomment the line below.
#pkg-config --exists libudev && udev=enable

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --disable-selinux \
    --enable-pkgconfig \
    --enable-fsadm \
    --enable-dmeventd \
    --enable-cmdlib \
    --enable-static_link \
    --with-default-dm-run-dir=/run \
    --with-default-locking-dir=/run/lock/lvm \
    --with-default-pid-dir=/run \
    --with-default-run-dir=/run/lvm \
    --"${udev:=enable}"-udev_sync \
    --"$udev"-udev_rules

make DESTDIR="$1" install

# Make all libraries and binaries writable.
chmod -R u+w "$1/usr/lib/" "$1/usr/bin/" "$1/usr/sbin/"
