#!/bin/sh -e

patch -p1 < remove_gettext.patch

export DESTDIR="$1" 

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dbuildtype=release \
    -Dsynctex=disabled \
    output
 
ninja -C output
ninja -C output install

mkdir -p "$1/usr/share/man/man1"
mkdir -p "$1/usr/share/man/man5"

cp zathura.1           "$1/usr/share/man/man1/zathura.1"
cp zathura-sandbox.1   "$1/usr/share/man/man1/zathura-sandbox.1"
cp zathurarc.5         "$1/usr/share/man/man5/zathurarc.5"
