#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-po.patch

sed 's|check:true|check:false|g' meson.build > _
mv -f _ meson.build

meson setup \
    --prefix=/usr \
    build

ninja -C build
ninja -C build install
