#!/bin/sh -e

export DESTDIR="$1"

sed 's|git.found()|false|g' meson.build > _
mv -f _ meson.build

meson \
    --prefix=/usr \
    -Ddefault_codec=libvpx-vp9 \
    . output

ninja -C output
ninja -C output install
