#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    --prefix=/usr \
    -Ddefault-wallpaper=false \
    -Dzsh-completions=false \
    -Dbash-completions=false \
    -Dfish-completions=false \
    -Dxwayland=disabled \
    . output

ninja -C output
ninja -C output install
