#!/bin/sh -e

# Stem is a python library for interacting with Tor.
(
    cd stem
    python3 setup.py build
    python3 setup.py install --root "$1"
)

python3 setup.py build
python3 setup.py install --root "$1"

# Install documentation manually, as setup.py doesn't do it.
install -D nyx.1 "$1/usr/share/man/man1/nyx.1"
