#!/bin/sh -e

./configure                               \
    --prefix=/usr                         \
    --sbindir=/usr/bin                    \
    --libexecdir=/usr/lib                 \
    --with-secure-path                    \
    --with-env-editor                     \
    --with-passprompt="[sudo] password for %p: "

make
make DESTDIR="$1" install
rm -rf "$1/usr/share/locale/"
