#!/bin/sh -e

go run build.go

install -Dm755 restic "$1/usr/bin/restic"
install -Dm644 doc/bash-completion.sh "$1/usr/share/bash-completion/completions/restic"
install -Dm644 doc/zsh-completion.zsh "$1/usr/share/zsh/site-functions/_restic"

for m in doc/man/*.1; do
    install -Dm644 "$m" "$1/usr/share/man/man1/${m##doc/man/}"
done
