#!/bin/sh -e

patch -p1 < CVE-2021-20255.patch

# Don't use bash
sed 's/SHELL = bash -o pipefail/SHELL = sh/g' Makefile > _
mv -f _ Makefile

# Build qemu-system* binaries dynamically linked
./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-debug-info \
    --disable-gtk \
    --disable-docs \
    --enable-sdl \
    --enable-kvm \
    --enable-pie \
    --enable-curses \
    --disable-user \
    --disable-linux-user \
    --enable-system

make
make PREFIX=/usr install
make clean

# Build qemu Linux user binaries statically linked.
./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --disable-debug-info \
    --disable-gtk \
    --disable-docs \
    --disable-user \
    --enable-linux-user \
    --disable-system \
    --static

make
make PREFIX=/usr install
