#!/bin/sh -e

make PREFIX=/usr

# 'make install' doesn't create the directory.
mkdir -p "$1/usr/include"
cp src/dictionary.h "$1/usr/include/dictionary.h"
cp src/iniparser.h  "$1/usr/include/iniparser.h"

mkdir -p "$1/usr/lib"
cp libiniparser.so.1    "$1/usr/lib/libiniparser.so.1"
ln -s libiniparser.so.1 "$1/usr/lib/libiniparser.so"
