#!/bin/sh -e

patch -p1 < fts.patch
cat <<EOF > fts/config.h
#define HAVE_DECL_MAX 1
#define HAVE_DECL_UINTMAX_MAX 0
#define HAVE_DIRFD 1
EOF

make O_NORL=1 strip
make DESTDIR="$1" PREFIX=/usr install
