#!/bin/sh -e

export DESTDIR="$1"

for p in *.patch; do
    patch -p1 < "$p"
done

sed "/subdir('po'/d" subprojects/wireplumber/meson.build > _
mv -f _ subprojects/wireplumber/meson.build

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddbus=disabled \
    -Dsndfile=enabled \
    -Djack=disabled \
    -Dpipewire-jack=disabled \
    -Dtests=disabled \
    -Dudev=enabled \
    -Dudevrulesdir=/usr/lib/udev/rules.d \
    -Dsession-managers=wireplumber \
    -Dwireplumber:system-lua=true \
    . output

ninja -C output
ninja -C output install
