#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Ddbus=disabled \
    -Dtests=disabled \
    -Dudev=enabled \
    -Dudevrulesdir=/usr/lib/udev/rules.d \
    . output

ninja -C output
ninja -C output install

:>"$1/usr/share/pipewire/media-session.d/with-alsa"
