#!/bin/sh -e

mkdir -p "$1/usr/bin" "$1/usr/lib/docker/cli-plugins"

chmod +x docker-compose-linux-x86_64

cp docker-compose-linux-x86_64 "$1/usr/lib/docker/cli-plugins/docker-compose"
ln -sf /usr/lib/docker/cli-plugins/docker-compose "$1/usr/bin/docker-compose"
