#!/bin/sh -e

export DESTDIR="$1"

meson \
	--prefix=/usr \
	-Dbackend-x11=disabled \
	-Dbackend-wayland=enabled \
	-Dplugin-mpd=disabled \
	--warnlevel 0 \
	. build
ninja -C build
ninja -C build install
