#!/bin/sh -e

patch -p1 < fix-ln.patch

./configure \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --with-xz \
    --with-zlib \
    --with-zstd \
    --disable-manpages

make
make DESTDIR="$1" install
