#!/bin/sh -e

export CFLAGS="$CFLAGS -std=gnu17"

./configure  \
    --prefix=/usr \
    --sbindir=/usr/bin \
    --sysconfdir=/etc \
    --disable-mutool 

make
make DESTDIR="$1" MAKEFLAGS="-j1" install
