#!/bin/sh -e

meson build \
  -Dprefix=/usr \
  -Dasm=enabled \
  -Dx11=disabled \
  -Degl=true \
  -Dglx=disabled \
  -Dgles1=true \
  -Dgles2=true \
  -Dtls=enabled \
  -Dheaders=true \
  -Dentrypoint-patching=enabled

ninja -C build
DESTDIR="$1" ninja -C build install
