#!/bin/sh -e

# This is a somewhat minimal build of neomutt. If you want more features
# like header cache and PGP support, you can view my personal package for
# an example: http://git.bvnf.space/kiss-repo/file/neomutt/build.html

# enable building with netbsd-curses
sed -i 's/tinfow tinfo/tinfow tinfo terminfo/g;/Unable to find xsltproc/d;
    s@xmlcatalog@/bin/true@' \
    auto.def

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --ssl \
    --sasl \
    --disable-nls \
    --disable-idn2 \
    --zlib

# Don't actually build the docs (some of the xsltproc html stuff requires
# an internet connection)
sed '/^.*_TARGETS=/s/ .*-docs//;s/xsltproc/:/g' Makefile > _
mv _ Makefile

make
make docs/neomuttrc docs/neomutt.1 docs/neomuttrc.5
make DESTDIR="$1" install

# Install the man pages and /etc/neomuttrc.
mkdir -p \
    "$1/etc" \
    "$1/usr/share/man/man1" \
    "$1/usr/share/man/man5"

cp -f docs/neomuttrc "$1/etc"
cp -f docs/neomutt.1 \
      docs/pgpewrap.1 \
      "$1/usr/share/man/man1/"
cp -f docs/neomuttrc.5 \
      docs/mbox.5 \
      docs/mmdf.5 \
      "$1/usr/share/man/man5/"
