#!/bin/sh -e

# Fixes for gcc 15
patch -p1 < gcc15_fixes.patch

./configure \
    --prefix=/usr \
    --disable-gtk \
    --disable-dbus \
    --with-drivers=ALL \
    --with-fontpaths=/usr/share/ghostscript/fonts/:/usr/share/fonts
	
make so all
make DESTDIR="$1" install-so install
