#!/bin/sh -e

export CGO_CPPFLAGS="${CPPFLAGS}"
export CGO_CFLAGS="${CFLAGS}"
export CGO_CXXFLAGS="${CXXFLAGS}"
export CGO_LDFLAGS="${LDFLAGS}"
export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw"
export GO111MODULE=on

go build \
    -o docker-buildx \
    -mod=vendor \
    ./cmd/buildx


mkdir -p "$1/usr/lib/docker/cli-plugins"
cp docker-buildx "$1/usr/lib/docker/cli-plugins/"
