#!/bin/sh -e

export GOPATH="$PWD/go"
export GO111MODULE=on

go build \
    -modcacherw \
    -trimpath \
    -o caddy ./cmd/caddy

install -Dm 755 caddy      "$1/usr/bin/caddy"
install -Dm 755 caddy.run  "$1/etc/sv/caddy/run"
install -Dm 755 caddy.conf "$1/etc/caddy/caddy.conf"

ln -sf /run/runit/supervise.caddy "$1/etc/sv/caddy/supervise"
