#!/bin/sh -e

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --libexecdir=/usr/lib \
    -Dintrospection=false \
    -Dgtkdoc=false \
    . output

ninja -C output
ninja -C output install

rm -rf "$1/usr/share/installed-tests" "$1/usr/lib/installed-tests"
